[package]
name = "lx-editor-utils"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
authors = ["LX Audiolabs"]
publish = false

[dependencies]
lx-aura = { workspace = true }
lx-aura-editor = { workspace = true, features = ["backend-femtovg"] }
paste = "1"
slint = { workspace = true }

[build-dependencies]
lx-aura-build = { workspace = true }
